import { escapeHtml } from '../ui/html.js';
export const NETWORK_RECIPES=[
 {id:'open',title:'1. Открыть порт и построить филиал',goal:'Оставить 100 ₽ оборотного резерва. Повторный запуск не покупает уже построенный цех.',methods:['cq.world.getRegions','cq.network.getCatalog','cq.network.open'],
  code:'export function main(cq) {\n  const region = cq.world.getRegions().find(r => r.id === "port");\n  let site = cq.network.getCatalog().find(s => s.id === "port");\n  if (!region.unlocked && cq.world.getState().balance >= region.cost + site.cost + 100) {\n    cq.world.explore("port");\n  }\n  site = cq.network.getCatalog().find(s => s.id === "port");\n  if (site.canOpen && cq.world.getState().balance >= site.cost + 100) cq.network.open(site.id);\n  console.log(cq.network.getSites());\n}'},
 {id:'produce',title:'2. Купить местное сырьё и произвести металл',goal:'В порту сырьё хранится отдельно. После запуска партии дождитесь ещё одного игрового шага.',methods:['cq.network.buy','cq.network.quoteProduction','cq.network.start'],
  code:'export function main(cq) {\n  if (!cq.network.getSites().some(s => s.id === "port")) { console.log("Сначала постройте портовой цех"); return; }\n  const site = cq.network.getSite("port");\n  const line = site.lines.find(l => !l.job);\n  if (!line) return;\n  const supplier = cq.market.getSuppliers().find(s => s.id === "port-yard");\n  const missing = Math.max(0, 10 - site.inventory.scrap);\n  if (supplier.stock < missing || site.freeSpace < missing || cq.world.getState().balance < missing * supplier.price + 10 + 100) return;\n  if (missing > 0) cq.network.buy("port", "scrap", missing, supplier.id);\n  const q = cq.network.quoteProduction("port", "metal", 5, line.id);\n  if (q.canStart) cq.network.start("port", "metal", 5, line.id);\n  else console.log(q.reasons);\n}'},
 {id:'transfer',title:'3. Перевезти продукцию на центральный склад',goal:'Перед отправкой проверьте транспорт и место назначения. Деньги списываются за перевозку, выручки пока нет.',methods:['cq.network.quoteTransfer','cq.network.transfer','cq.network.getTransfers'],
  code:'export function main(cq) {\n  if (!cq.network.getSites().some(s => s.id === "port")) return;\n  const q = cq.network.quoteTransfer("metal", 5, "port", "city");\n  if (q.canDispatch) cq.network.transfer("metal", 5, "port", "city");\n  else console.log(q.reasons);\n  console.log(cq.network.getTransfers());\n}'},
 {id:'compare',title:'4. Сравнить специализации цехов',goal:'Порт уменьшает энергию деталей на 2 ₽ за единицу. Север сокращает сборку схем на один шаг. Исследования складываются с бонусом; длительность не меньше одного шага.',methods:['cq.network.quoteProduction','cq.network.quoteTrade'],
  code:'export function main(cq) {\n  for (const site of cq.network.getSites()) {\n    const q = cq.network.quoteProduction(site.id, "parts", 1);\n    console.log(site.id, "энергия:", q.energyCost, "время:", q.duration, "причины:", q.reasons);\n  }\n}'}
];
export function mountNetworkGuide(root,onMethod){
 root.innerHTML='<h3>От одного склада к сети предприятий</h3><p>Регион и цех — разные покупки. Сначала откройте регион, затем постройте площадку. Баланс, исследования и спрос покупателей общие; inventory и lines у каждого цеха свои. Имена линий повторяются, поэтому сетевым командам нужен siteId.</p><ol><li>Центр: прежняя мастерская и городской контрактный склад.</li><li>Порт: дешёвый местный лом, более дешёвая энергия деталей и прямые продажи портовым покупателям.</li><li>Север: местный металл и ускоренное производство схем для северных покупателей.</li></ol><p>Прежние cq.market, cq.factory и cq.warehouse работают с центральной мастерской. market.buy сохраняет прежнюю закупку в центральный склад у доступного поставщика. В network.buy поставщик должен находиться в регионе площадки. Используйте network.transfer для перемещения собственных запасов.</p>'+NETWORK_RECIPES.map(r=>'<details class="city-guide-recipe"><summary>'+r.title+'</summary><p>'+r.goal+'</p><pre data-network-guide-code="'+r.id+'">'+escapeHtml(r.code)+'</pre><button type="button" data-network-guide-copy="'+r.id+'">Копировать main</button><div class="city-guide-methods">'+r.methods.map(method=>'<button type="button" data-network-guide-method="'+method+'">'+method+'</button>').join('')+'</div></details>').join('')+'<h3>Как избежать ошибок диспетчера</h3><ul><li>Не считайте inbound готовым товаром. Он уже резервирует склад, но ещё не прибыл.</li><li>Груз сохраняет arrivesAt при улучшении транспорта или исследовании logistics. Новые грузы используют новые условия.</li><li>Перевозка оплачивается один раз. Цена: 2 × duration + quantity. fleet.capacity относится к одной машине; fleet.slots — к числу одновременных грузов.</li><li>После каждого действия общий баланс и локальные запасы меняются. Проверяйте quote перед следующей командой.</li><li>В конце шага завершается производство, прибывают внутренние грузы, затем исполняются отложенные продажи центрального склада.</li><li>В render доступны чтения и quote, команды запрещены. В конструкторе выберите «Сеть предприятия»: он создаст таблицы складов, перевозок, загрузку и график с фильтром площадки.</li></ul><p>Во вкладке «Задания» маршрут продолжают задания 14–17. Для эксперимента начните с пробного запуска; все действия и изменения памяти откатываются при ошибке.</p><p data-network-guide-status role="status" class="city-muted"></p>';
 root.querySelectorAll('[data-network-guide-method]').forEach(button=>button.onclick=()=>onMethod(button.dataset.networkGuideMethod));
 root.querySelectorAll('[data-network-guide-copy]').forEach(button=>button.onclick=async()=>{
  const recipe=NETWORK_RECIPES.find(r=>r.id===button.dataset.networkGuideCopy),status=root.querySelector('[data-network-guide-status]');
  try{await navigator.clipboard.writeText(recipe.code);status.textContent='Скопировано. Проверьте пример в index.js пробным запуском.';}
  catch{const range=document.createRange();range.selectNodeContents(root.querySelector('[data-network-guide-code="'+recipe.id+'"]'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);status.textContent='Код выделен. Скопируйте вручную.';}
 });
}
